// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type Image struct {
	ID       uuid.UUID
	ImageUrl string
}

type Playlist struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
}

type Post struct {
	ID          uuid.UUID
	Title       string
	PostUrl     string
	Content     string
	YoutubeLink sql.NullString
}

type Tutorial struct {
	ID          uuid.UUID
	Title       string
	TutorialUrl string
	Description string
	YoutubeLink string
	PlaylistID  uuid.UUID
}
