name: Test on all Pushes 
on:
  push :
   branches: 
     [main,  dev]


permissions:
 checks: write
 contents: read
 pull-requests: write
jobs:
    run-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Run all test
              run: go test

