name: Test On Pull request to main
on:
  pull_request :
   branches: 
     main


permissions:
 checks: write
 contents: read
 pull-requests: write
jobs:
 build_and_preview:

   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v4
    - name: Setup Go 
      uses: actions/setup-go@v5
    - name: Run tests
      run: go test